Minor styling changes
cscott/jsdoc-wmf-theme pull request #3
Opened 2018-07-11 04:23 UTC by prtksxna

2018-07-12 14:16 UTC, cscott requested changes
(Also: should I just import this repo into gerrit?)

2018-07-12 14:16 UTC, cscott commented on static/styles/jsdoc-wmf-theme.css
>  /* tweak so summary and description have same top margin */
Maybe update this comment?

2018-07-13 04:41 UTC, prtksxna commented on static/styles/jsdoc-wmf-theme.css
>  /* tweak so summary and description have same top margin */
Done

2018-07-13 04:50 UTC, prtksxna commented
These styling changes don't work completely well with `plugins/summarize`, working on that now.

2018-07-13 12:29 UTC, prtksxna commented
> (Also: should I just import this repo into gerrit?)

I guess so 🙂

2018-07-13 15:28 UTC, cscott commented
Is this ready to go now?

2018-07-13 17:02 UTC, prtksxna commented
Yes!

2018-07-13 17:21 UTC, merged

2018-07-14 03:41 UTC, prtksxna commented
> (Also: should I just import this repo into gerrit?)

We'll still be able to `npm install` from the gerrit git end point, right?

2018-07-14 05:58 UTC, cscott commented
I think all our gerrit repos get github mirrors?
And fwiw I released 0.0.2 via npm.